---
title: "ASLeaf ITS"
author: "JReceveur"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: true
editor_options: 
  chunk_output_type: console
---
  
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.width=14, fig.height=10)
knitr::opts_chunk$set(fig.align="center")
```




# Import{.tabset}

## Sample Overview

```{r,warning=F,include=F}
#From https://gist.github.com/grabear/018e86413b19b62a6bb8e72a9adba349
#Parse Silva function

parse_taxonomy_silva_138 <- function(char.vec){
  # Use default to assign names to elements in case problem with greengenes prefix
  char.vec = parse_taxonomy_default(char.vec)
  # Check for unassigned taxa
  if (char.vec["Rank1"] == "Unassigned") {
    char.vec <- c(Rank1="d__Unassigned", Rank2="d__Unassigned", Rank3="d__Unassigned", Rank4="d__Unassigned",
                  Rank5="d__Unassigned", Rank6="d__Unassigned", Rank7="d__Unassigned")
  }
  # Define the meaning of each prefix according to SILVA taxonomy
  Tranks = c(Rank1="Kingdom", Rank2="Phylum", Rank3="Class", Rank4="Order", Rank5="Family", Rank6="Genus", Rank7="Species")
  # Check for prefix using regexp, warn if there were none. trim indices, ti
  ti = grep("[[:alpha:]]\\_\\_", char.vec)
  if( length(ti) == 0L ){
    warning(
      "No silva prefixes were found. \n",
      "Consider using parse_taxonomy_delfault() instead if true for all OTUs. \n",
      "Dummy ranks may be included among taxonomic ranks now."
    )
    # Will want to return without further modifying char.vec
    taxvec = char.vec
    # Replace names of taxvec according to prefix, if any present...
  } else {
    # Format character vectors for Ambiguous taxa
    if( length(ti) < 7 ){
      for (key in names(char.vec)) {
        if ( char.vec[key] == "Ambiguous_taxa" ) {
          tax_no <- (as.numeric(substr(key, 5, 5)) - 1)
          char.vec[key] = sprintf("d__Ambiguous_taxa", tax_no)
        }
      }
      # Reset the trimmed indicies if Ambiguous taxa
      ti = grep("[[:alpha:]]\\_\\_", char.vec)
    }
    # Remove prefix using sub-"" regexp, call result taxvec
    taxvec = gsub("[[:alpha:]]\\_\\_", "", char.vec)
    # Define the ranks that will be replaced
    repranks = Tranks[substr(char.vec[ti], 1, 3)]
    # Replace, being sure to avoid prefixes notK present in Tranks
    names(taxvec)[ti[!is.na(repranks)]] = repranks[!is.na(repranks)]
  }
  return(taxvec)
}




library(vegan)
library(ggplot2)
library(plyr)
library(dplyr)
library(phyloseq)
library(randomForest)
library(knitr)




set.seed(10)
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#000000","#CC79A7") #Build a user defined colorblind palette



theme_set(theme_bw(base_size = 18)+theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())) #Set font size and change default plot theme

biom=import_biom("ASLeafJan2021ITS_6k.biom",parseFunction=parse_taxonomy_silva_138) #Import biom file which contains taxa names and abundances 
colnames(tax_table(biom))<-c(Rank1="Kingdom", Rank2="Phylum", Rank3="Class", Rank4="Order", Rank5="Family", Rank6="Genus", Rank7="Species")




metadata=read.table("LauraMetadata9Dec2020.txt",header = TRUE)

metadata$Date = factor(metadata$Date, levels = c("3_1","24_1","14_2","7_3","29_3","19_4")) #fixes x-axis labels
metadata$Paired<-paste0(metadata$Site,metadata$Date)

tree=read_tree("ASLeafTreeDec2020.nwk")

sampdat=sample_data(metadata)
sample_names(sampdat)=metadata$ID # If using fungal data change ID to FungalID
physeq=merge_phyloseq(biom,sampdat,tree)
physeq<-filter_taxa(physeq, function (x) {sum(x > 0) > 1}, prune=TRUE)#Remove zeros
physeq<-subset_samples(physeq, Site!="<NA>") # Remove Control
physeq
#physeq 



GPr  = transform_sample_counts(physeq, function(x) x / sum(x) ) #transform samples based on relative abundance
PhylumAll=tax_glom(GPr, "Phylum")

PhylumLevel = filter_taxa(PhylumAll, function(x) mean(x) > 3e-2, TRUE) #filter out any taxa lower than 3%
FamilyAll=tax_glom(GPr,"Family")
FamilyLevel = filter_taxa(FamilyAll, function(x) mean(x) > 3e-2, TRUE) #filter out any taxa lower than 3%
GenusAll=tax_glom(GPr,"Genus")
GenusLevel = filter_taxa(GenusAll, function(x) mean(x) > 2e-2, TRUE) #filter out any taxa lower than 2%

```

Unique fungal ASVs between leaf types
```{r}
df <- psmelt(physeq)
head(df)
length(unique(df$OTU))

OakSubset<-subset(df,Treatment=="Q")
OakSubset<-subset(OakSubset,Abundance!=0)
length(unique(OakSubset$OTU))

ChestnutSubset<-subset(df,Treatment=="C")
ChestnutSubset<-subset(ChestnutSubset,Abundance!=0)
length(unique(ChestnutSubset$OTU))

length(intersect(OakSubset$OTU,ChestnutSubset$OTU)) #2228


length(setdiff(ChestnutSubset$OTU,OakSubset$OTU)) #311 ASVs in Chestnut but not in Oak
length(setdiff(OakSubset$OTU,ChestnutSubset$OTU)) # 454 ASVs in Oak but not in Chestnut


## Unique ASVs by day

#########
# Day 21
#########

Timepoint1<-subset_samples(physeq,Days==21)
df1 <- psmelt(Timepoint1)

OakSubset1<-subset(df1,Treatment=="Q")
OakSubset1<-subset(OakSubset1,Abundance!=0)
length(unique(OakSubset1$OTU)) #1106

ChestnutSubset1<-subset(df1,Treatment=="C")
ChestnutSubset1<-subset(ChestnutSubset1,Abundance!=0)
length(unique(ChestnutSubset1$OTU)) #1108

length(intersect(OakSubset1$OTU,ChestnutSubset1$OTU)) #594
length(union(OakSubset1$OTU,ChestnutSubset1$OTU)) #1520

length(setdiff(ChestnutSubset1$OTU,OakSubset1$OTU)) #414 ASVs in Chestnut but not in Oak
length(setdiff(OakSubset1$OTU,ChestnutSubset1$OTU)) # 512 ASVs in Oak but not in Chestnut

#########
# Day 126
#########

Timepoint126<-subset_samples(physeq,Days==126)
df126 <- psmelt(Timepoint126)

OakSubset126<-subset(df126,Treatment=="Q")
OakSubset126<-subset(OakSubset126,Abundance!=0)
length(unique(OakSubset126$OTU)) #1530

ChestnutSubset126<-subset(df126,Treatment=="C")
ChestnutSubset126<-subset(ChestnutSubset126,Abundance!=0)
length(unique(ChestnutSubset126$OTU)) #1534

length(intersect(OakSubset126$OTU,ChestnutSubset126$OTU)) #1095
length(union(OakSubset126$OTU,ChestnutSubset126$OTU)) #1969

length(setdiff(ChestnutSubset126$OTU,OakSubset126$OTU)) #439 ASVs in Chestnut but not in Oak at day 126
length(setdiff(OakSubset126$OTU,ChestnutSubset126$OTU)) # 435 ASVs in Oak but not in Chestnut at day 126

```

